on: [push]
name: oaiJats
jobs:
  oaiJats:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - application: ojs
            php-version: 7.3
            database: mysql
          - application: ojs
            php-version: 7.4
            database: mysql
          - application: ojs
            php-version: 8.0
            database: mysql
          - application: ojs
            php-version: 7.3
            database: pgsql
          - application: ojs
            php-version: 7.4
            database: pgsql
          - application: ojs
            php-version: 8.0
            database: pgsql

    name: oaiJats
    steps:
      - uses: pkp/pkp-github-actions@v1
        with:
         node_version: 20
         branch: main
         repository: pkp

      - name: Install plugin for push
        if: ${{  github.event_name  == 'push'}}
        run: |
          cd ~/${{matrix.application}}/plugins/oaiMetadataFormats
          git clone -b ${{ github.head_ref || github.ref_name }} https://github.com/${{ github.repository}} ${{ github.event.repository.name }}  --depth 1
        shell: bash

      - name: Install plugin for pull_request
        if: ${{github.event_name  == 'pull_request'}}
        run: |
          cd ~/${{matrix.application}}/plugins/oaiMetadataFormats
          git clone -b ${{ github.event.pull_request.head.ref}} ${{ github.event.pull_request.head.repo.html_url}} ${{ github.event.pull_request.head.repo.name }} --depth 1
        shell: bash

      - name: Install from datasets
        run: |
          cd ~/${{matrix.application}}/
          git clone  https://github.com/pkp/datasets  datasets --depth 1
          cp -rf datasets/${APPLICATION}/${BRANCH}/${TEST}/public/* public/
          cp -rf datasets/${APPLICATION}/${BRANCH}/${TEST}/files/* files/
          cat datasets/${APPLICATION}/${BRANCH}/${TEST}/database.sql | ./datasets/tools/dbclient.sh

        shell: bash
        env:
          APPLICATION: ${{matrix.application}}
          BRANCH: main
          TEST: ${{matrix.database}}
          DBTYPE: ${{matrix.database == 'pgsql' && 'PostgreSQL' || 'MySQLi'}}
          DBHOST: localhost
          DBNAME: ${{matrix.application}}-ci
          DBUSERNAME: ${{matrix.application}}-ci
          DBPASSWORD: ${{matrix.application}}-ci

      - name: Run Plugin installation
        run: |
          php lib/pkp/tools/installPluginVersion.php plugins/generic/jatsTemplate/version.xml
          php lib/pkp/tools/installPluginVersion.php plugins/oaiMetadataFormats/oaiJats/version.xml
        shell: bash
      - name : Run Cypress tests
        run: |
          $(npm bin)/cypress run --config '{"specPattern":["plugins/oaiMetadataFormats/oaiJats/cypress/tests/functional/*.cy.js"]}'
        shell: bash

      - name: Fetch a JATS document through oaiJats, removing the OAI-PMH wrapper using xmlstarlet
        run: |
          get -q -O - "http://localhost/index.php/publicknowledge/oai?verb=ListRecords&metadataPrefix=jats" | xmlstarlet sel -N x="https://jats.nlm.nih.gov/publishing/1.1/" -t -c "(//x:article)[1]" > jats.xml
          python3 plugins/oaiMetadataFormats/oaiJats/validate.py jats.xml erudit-style-0.3.sch
        shell: bash

      - name: Setup tmate session by failure
        if: ${{ failure()}}
        uses: mxschmitt/action-tmate@v3


      


     